package de.fhg.fokus.ims.core.auth.AKAISIM;

import de.fhg.fokus.ims.core.auth.AKA.DigestAKA;
import de.fhg.fokus.ims.core.auth.AKA.DigestAKAResponse;


/**
 * 
 * This class represents a response to a AKA challenge, as generated by DigestAKA.
 * 
 * @author FhG FOKUS <a href="mailto:openic@open-ims.org">openic@open-ims.org</a>
 *
 */
public class DigestAKAResponseImpl implements DigestAKAResponse
{
	private String response,auts;
	private byte[] res,ck,ik;
	private boolean isSynchronization;
	private boolean unauthorizedChallenge;
	private byte[] newSQN;
	private boolean isSqnMS;
	
	/**
	 * @param synchronization
	 * @param value
	 */
	public DigestAKAResponseImpl(String response,String auts,boolean isSynchronization,
			boolean unauthorizedChallenge,byte[] newSQN,
			boolean isSqnMS, byte[] res,byte[] ck, byte[] ik) {
		this.isSynchronization = isSynchronization;
		this.response = response;
		this.auts = auts;
		this.unauthorizedChallenge = unauthorizedChallenge;
		this.newSQN = newSQN;
		this.isSqnMS = isSqnMS;
		this.res = res;
		this.ck = ck;
		this.ik = ik;
	}

	public String getResponse()
	{
		return response;
	}

	public String getAuts()
	{
		return auts;
	}

	public byte[] getRes()
	{
		return res;
	}

	public byte[] getCk()
	{
		return ck;
	}

	public byte[] getIk()
	{
		return ik;
	}

	public boolean isSynchronization()
	{
		return isSynchronization;
	}

	public boolean isUnauthorizedChallenge()
	{
		return unauthorizedChallenge;
	}

	public byte[] getNewSQN()
	{
		return newSQN;
	}

	public boolean isSqnMS()
	{
		return isSqnMS;
	}

	
	public String toString() {
		StringBuffer stb = new StringBuffer();
		stb.append("RES = ");
		stb.append(response);
		stb.append("\nAUTS = ");
		stb.append(auts);
		stb.append("\nisSynchronization = ");
		stb.append(isSynchronization);
		stb.append("\nunauthorizedChallenge = ");
		stb.append(unauthorizedChallenge);
		stb.append("\nnewSQN = ");
		stb.append(new String(DigestAKA.bin2hexa(newSQN)));
		stb.append("\nisSqnMS = ");
		stb.append(this.isSqnMS);
		stb.append("\nCK = ");
		stb.append(new String(DigestAKA.bin2hexa(ck)));
		stb.append("\nIK = ");
		stb.append(new String(DigestAKA.bin2hexa(ik)));
		return stb.toString();
	}

}

