/*
 * Copyright (C) 2007 FhG FOKUS, Institute for Open Communication Systems
 *
 * This file is part of OpenIC - an IMS user endpoint implementation
 * 
 * OpenIC is proprietary software that is licensed 
 * under the FhG FOKUS "SOURCE CODE LICENSE for FOKUS IMS COMPONENTS".
 * You should have received a copy of the license along with this 
 * program; if not, write to Fraunhofer Institute FOKUS, Kaiserin-
 * Augusta Allee 31, 10589 Berlin, GERMANY 
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * It has to be noted that this software is not intended to become 
 * or act as a product in a commercial context! It is a PROTOTYPE
 * IMPLEMENTATION for IMS technology testing and IMS application 
 * development for research purposes, typically performed in IMS 
 * test-beds. See the attached license for more details. 
 *
 * For a license to use this software under conditions
 * other than those described here, please contact Fraunhofer FOKUS 
 * via e-mail at the following address:
 * 
 *    info@open-ims.org
 *
 */
package de.fhg.fokus.ims.core.auth.MD5;


/**
 * 
 * This class represents a response to a MD5 challenge, as generated by DigestMD5.
 * 
 * @author FhG FOKUS <a href="mailto:openic@open-ims.org">openic@open-ims.org</a>
 *
 */
public class DigestMD5Response 
{

	
	public String response;
	public byte[] res;
	public String qop=null;
	public String cNonce=null;
	public int nonceCount=0;
	
	public DigestMD5Response(String response,byte[] res, String qop,
			String cNonce, int nonceCount ) {
		this.response = response;
		this.res = res;
		if (qop==null || qop.length()==0) 
			this.qop = null;
		else 
			this.qop = qop;
		this.cNonce = cNonce;
		this.nonceCount = nonceCount;
	}
	
	public String toString() {
		StringBuffer stb = new StringBuffer();
		stb.append("RES = ");
		stb.append(response);
		stb.append("  QoP = ");
		stb.append(qop);
		return stb.toString();
	}

}
